experiment_name: ray-esm2-embed-e2fe
environment:
  dependencies: dependencies.yaml
  env_variables:
    NCCL_NET_PLUGIN: "none"
    NUM_WORKERS: "1"
    BATCH_SIZE: "32"
    MAX_LENGTH: "1024"
    ESM2_MODEL: "facebook/esm2_t33_650M_UR50D"
    INPUT_STAGE_DIR:      "/Volumes/users/guanyu_chen/sgc/ray_input_stage"
    OUTPUT_STAGE_PARQUET: "/Volumes/users/guanyu_chen/sgc/ray_output_stage_parquet_w1"
compute:
  gpus: 1
  gpu_type: a10
max_retries: 0
code_source:
  type: snapshot
  snapshot:
    allow_uncommitted: true
    repo_path: <UPDATE_THIS_to_local_path_of_sgcli-inference>
    include_paths:
      - ray_esm2_embed
command: |-
  echo ">>> ESM-2 batch embedding via Ray Data on SGC (e2FE)"
  python3 $CODE_SOURCE_PATH/sgcli-inference/ray_esm2_embed/embed.py
